insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10002,'USD','INR','91','');
insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10003,'EUR','INR','113','');
insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10004,'AUD','INR','25','');